### PR TITLE
Added Flurl and Flurl.Http

### PR DESCRIPTION
**Pull request by tmenier**

### CODE REVIEW

**Comment by tallesl** [comment]
Since the homepage and the repository are the same on both I kept only the first.

Merged :+1:

**Comment by tmenier** [comment]
Works for me, thanks for adding!

**Comment by tmenier** [comment]
Actually, could I make a suggestion regarding the NuGet link? Flurl technically comes in 4 flavors: just the URL builder, URL builder + HTTP client, and signed versions of both. Linking to the core Flurl gives you just the URL builder, which could be confusing since the description mentions HTTP. Possible alternatives:
- 2 NuGet links: https://www.nuget.org/packages/Flurl & https://www.nuget.org/packages/Flurl.Http
- link to just Flurl.Http (since it includes the base package): https://www.nuget.org/packages/Flurl.Http
- link to all 4 via search: https://www.nuget.org/packages?q=flurl

Do you have a preference? I couldn't find a comparable example on your list. Thanks!

**Comment by tallesl** [comment]
Changed to the http one them.

I hope you understand on me insisting on keeping a single reference.
Most of the libraries and frameworks in the list have many packages and flavors, putting them all would make the list seem more like a catalog them a curated thing.

**Comment by tmenier** [comment]
That's perfect, and totally understood. Thanks again!

**Pull request closed without merging**
